<?php
/*
 *   FactionsPE: PocketMine-MP Plugin
 *   Copyright (C) 2020 BlockHorizons
 */

namespace fpe\data;

use Exception;
use fpe\entity\IMember;
use fpe\FactionsPE;
use fpe\flag\Flag;
use fpe\manager\Factions;
use fpe\permission\Permission;
use localizer\Localizer;
use pocketmine\level\Position;

class FactionData extends Data
{

    /**
     * @var string
     */
    protected $name;

    /**
     * Generated by FactionsPE::generateFactionID();
     * @var string
     */
    protected $id;

    /**
     * @var array $flags Flag => bool
     */
    protected $flags = [];

    /**
     * The perm overrides are modifications to the default values.
     * @var mixed[]
     */
    protected $perms = [];

    /**
     * Why not to save Member instances here? Because we need to get fresh one from storage
     * in case it changes
     *
     * @var string[]
     */
    protected $members = [];

    /**
     * Factions can optionally set a description for themselves.
     * This description can for example be seen in territorial alerts.
     * Null means the faction has no description.
     * @var string
     */
    protected $description;

    /**
     * Factions can optionally set a message of the day.
     * This message will be shown when logging on to the server.
     * Null means the faction has no motd
     * @var string $motd
     */
    protected $motd;

    /**
     * We store the creation date for the faction. It can be displayed on info pages etc.
     * @var int $createdAt
     */
    protected $createdAt;

    /**
     * Factions can optionally set a home location.
     * If they do their members can teleport there using /f home
     * Null means the faction has no home.
     * @var Position|null
     */
    protected $home;

    /**
     * Factions usually do not have a powerboost. It defaults to 0.
     * The powerBoost is a custom increase/decrease to default and maximum power.
     * Null means the faction has powerBoost (0).
     * @var int
     */
    protected $powerBoost = 0;

    /**
     * Faction ID => Relation ID
     * @var array $relationWishes
     */
    protected $relationWishes = [];

    /**
     * This holds player name, if the player name is in this list then he is invited
     * to this faction
     * @var string[]
     */
    protected $invitedPlayers = [];

    /**
     * If economy is enabled then members are able to deposit and withdraw from
     * faction bank account
     * @var int
     */
    protected $bank = 0;

    /**
     * Time faction has been online
     * @var int
     */
    protected $timeOnline = 0;

    /**
     * Time first player has joined and faction until then has been considered offline
     * @var int|null
     */
    protected $joined = null;

    /**
     * Time last online player has left the server and faction is now considered offline
     * @var int|null
     */
    protected $left = null;

    public function __construct(array $source)
    {
        // required fields
        $this->name = $source["name"];
        $this->id = $source["id"];
        // optional fields
        $this->members = $source["members"] ?? [];
        $this->createdAt = $source["createdAt"] ?? time();
        $this->description = $source["description"] ?? null;
        $this->motd = $source["motd"] ?? null;
        $this->powerBoost = $source["powerBoost"] ?? $this->powerBoost;
        $this->invitedPlayers = $source["invitedPlayers"] ?? [];
        $this->perms = $source["perms"] ?? [];
        $this->flags = $source["flags"] ?? [];
        $this->relationWishes = $source["relationWishes"] ?? [];
        $this->bank = $source["bank"] ?? $this->bank;

        foreach ($this->members as $rank => $members) {
            foreach ($members as $key => $mem) {
                if ($mem instanceof IMember) {
                    $this->members[$rank][$key] = $mem->getName();
                }
            }
        }

        foreach ($this->flags as $flag => $value) {
            if ($value instanceof Flag) {
                unset($this->flags[$flag]);
                $this->flags[$value->getId()] = $value->isStandard();
            }
        }

        foreach ($this->perms as $perm => $value) {
            if ($value instanceof Permission) {
                unset($this->perms[$perm]);
                $this->perms[$value->getName()] = $value->getStandard();
            }
        }

        if (isset($source["home"])) {
            $p = explode(":", $source["home"]);
            if (($level = FactionsPE::get()->getServer()->getLevelByName($p[3]))) {
                $this->home = new Position((float)$p[0], (float)$p[1], (float)$p[2], $level);
            } else {
                FactionsPE::get()->getLogger()->warning(Localizer::trans("plugin.faction-load-invalid-level", [$this->name, $source["home"]]));
            }
        }
    }

    /**
     * Puts all faction data, necessary to save, into array
     */
    public function __toArray(): array
    {
        $ret = [
            "name" => $this->name,
            "id" => $this->id,
            "flags" => $this->flags,
            "perms" => $this->perms,
            "members" => $this->members,
            "powerBoost" => $this->powerBoost,
            "relationWishes" => $this->relationWishes,
            "createdAt" => $this->createdAt,
            "motd" => $this->motd,
            "description" => $this->description,
            "invitedPlayers" => $this->invitedPlayers,
            "bank" => $this->bank,
            "timeOnline" => $this->timeOnline,
        ];

        if (($home = $this->getHome())) {
            $ret["home"] = $home->x . ":" . $home->y . ":" . $home->z . ":" . $home->level->getName();
        }
        return $ret;
    }

    public function getHome()
    {
        return $this->home;
    }

    public function setHome(Position $home)
    {
        $this->home = $home;
        $this->save();
    }

    public function save()
    {
        if (($faction = Factions::getById($this->id))) {
            FactionsPE::get()->getDataProvider()->saveFaction($faction);
        } else {
            throw new Exception("faction data is not assigned to valid faction");
        }
    }

    public function getFlags(): array
    {
        return $this->flags;
    }

    public function getPermissions(): array
    {
        return $this->perms;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function getDescription(): string
    {
        return $this->description ?? "";
    }

    public function setDescription(string $description)
    {
        $this->description = $description;
    }

    public function hasDescription(): bool
    {
        return $this->description !== null;
    }

    public function removeDescription()
    {
        $this->description = null;
    }

    public function getMotd()
    {
        return $this->motd;
    }

    public function setMotd(string $motd)
    {
        $this->motd = $motd;
    }

    public function hasMotd(): bool
    {
        return $this->motd !== null;
    }

    public function removeMotd()
    {
        $this->motd = null;
    }

    public function hasHome(): bool
    {
        return $this->home instanceof Position && $this->home->isValid();
    }

    public function isHomeSet(): bool
    {
        return $this->home instanceof Position;
    }

    public function getAge(): int
    {
        return time() - $this->getCreatedAt();
    }

    public function getCreatedAt(): int
    {
        return $this->createdAt;
    }

    public function getPowerBoost(): int
    {
        return $this->powerBoost;
    }

    public function setPowerBoost(int $power)
    {
        $this->powerBoost = $power;
    }

    public function hasPowerBoost(): bool
    {
        return $this->powerBoost === 0;
    }

    public function getRawMembers(): array
    {
        return $this->members;
    }

    public function setRawMembers(array $members)
    {
        $this->members = $members;
    }

    public function getRelationWishes(): array
    {
        return $this->relationWishes;
    }

    public function getInvitedPlayers(): array
    {
        return $this->invitedPlayers;
    }

    public function getBank(): int
    {
        return $this->bank;
    }

    public function setBank(int $value)
    {
        $this->bank = $value;
    }

    public function addToBank(int $value)
    {
        $this->bank += $value;
    }

    public function startCountingOnlineTime(): int
    {
        $this->joined = time();
        return $this->getOnlineTime();
    }

    public function getOnlineTime(): int
    {
        return $this->timeOnline = time() - $this->joined;
    }

    public function stopCountingOnlineTime(): int
    {
        $this->left = time();
        return $this->getOnlineTime();
    }

    public function getTimeJoined(): ?int
    {
        return $this->joined;
    }

    public function getTimeLeft(): ?int
    {
        return $this->left;
    }

}
